fixtures:
  repositories:
    apache:        "https://github.com/puppetlabs/puppetlabs-apache.git"
    augeas_core:
      repo: 'https://github.com/puppetlabs/puppetlabs-augeas_core'
      puppet_version: '>= 6.0.0'
    stdlib:        "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    extlib:        "https://github.com/voxpupuli/puppet-extlib"
    concat:        "https://github.com/puppetlabs/puppetlabs-concat.git"
    cron_core:
      repo: "https://github.com/puppetlabs/puppetlabs-cron_core"
      puppet_version: ">= 6.0.0"
    datacat:       "https://github.com/richardc/puppet-datacat"
    candlepin:     "https://github.com/theforeman/puppet-candlepin.git"
    foreman_proxy: "https://github.com/theforeman/puppet-foreman_proxy.git"
    foreman:       "https://github.com/theforeman/puppet-foreman"
    katello:       "https://github.com/theforeman/puppet-katello"
    tftp:          "https://github.com/theforeman/puppet-tftp"
    xinetd:        "https://github.com/puppetlabs/puppetlabs-xinetd"
    certs:         "https://github.com/theforeman/puppet-certs.git"
    qpid:          "https://github.com/theforeman/puppet-qpid.git"
    pulpcore:      "https://github.com/theforeman/puppet-pulpcore.git"
    postgresql:    "https://github.com/puppetlabs/puppetlabs-postgresql"
    redis:         "https://github.com/voxpupuli/puppet-redis"
    trusted_ca:    "https://github.com/voxpupuli/puppet-trusted_ca.git"
    selinux:       "https://github.com/voxpupuli/puppet-selinux.git"
    selinux_core:
      repo: "https://github.com/puppetlabs/puppetlabs-selinux_core"
      puppet_version: ">= 6.0.0"
    systemd:       'https://github.com/camptocamp/puppet-systemd'
    yumrepo_core:
      repo: "https://github.com/puppetlabs/puppetlabs-yumrepo_core"
      puppet_version: ">= 6.0.0"
