fixtures:
  repositories:
    apache:        "https://github.com/puppetlabs/puppetlabs-apache.git"
    stdlib:        "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    extlib:        "https://github.com/puppet-community/puppet-extlib"
    concat:        "https://github.com/puppetlabs/puppetlabs-concat.git"
    datacat:       "https://github.com/richardc/puppet-datacat"
    foreman_proxy: "https://github.com/theforeman/puppet-foreman_proxy.git"
    foreman:       "https://github.com/theforeman/puppet-foreman"
    puppet:        "https://github.com/theforeman/puppet-puppet"
    tftp:          "https://github.com/theforeman/puppet-tftp"
    xinetd:        "https://github.com/puppetlabs/puppetlabs-xinetd"
    certs:         "https://github.com/theforeman/puppet-certs.git"
    qpid:          "https://github.com/theforeman/puppet-qpid.git"
    pulp:          "https://github.com/theforeman/puppet-pulp.git"
    mongodb:       "https://github.com/puppetlabs/puppetlabs-mongodb.git"
    trusted_ca:    "https://github.com/evenup/evenup-trusted_ca.git"
    squid3:        "https://github.com/thias/puppet-squid3.git"
    systemd:       "https://github.com/camptocamp/puppet-systemd.git"
